sudo: false
language: scala
notifications:
  irc:
    channels:
      - "irc.freenode.org#argonaut"
    skip_join: true
    template:
      - "\x0313argonaut\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
matrix:
  include:
    - jdk: openjdk7
      scala: 2.10.7
      script: sbt ++${TRAVIS_SCALA_VERSION} test
    - jdk: oraclejdk8
      scala: 2.10.7
      script: sbt ++${TRAVIS_SCALA_VERSION} test

    - jdk: openjdk7
      scala: 2.11.12
      script: sbt ++${TRAVIS_SCALA_VERSION} test:compile jvmParent/test # scala-js test unstable with java7
    - jdk: oraclejdk8
      scala: 2.11.12
      script: sbt ++${TRAVIS_SCALA_VERSION} test:compile jvmParent/test "project jsParent" testSequential

    - jdk: oraclejdk8
      scala: 2.12.6
      script: sbt ++${TRAVIS_SCALA_VERSION} test:compile jvmParent/test "project jsParent" testSequential

    - jdk: oraclejdk8
      scala: 2.13.0-M4
      script: sbt ++${TRAVIS_SCALA_VERSION} argonautJVM/test argonaut-scalazJVM/test argonaut-catsJVM/test argonautJS/test argonaut-scalazJS/test argonaut-catsJS/test argonaut-jawnJVM/test

    - scala: 2.11.12
      jdk: oraclejdk8
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -
      script:
      - ./sbt ++$TRAVIS_SCALA_VERSION nativeTest/nativeLink
      - ./native-test/target/scala-2.11/nativetest-out
